// Data derived from flag_order.txt and COUNTRY_CODES in your files
const regions = [
    { name: "Anglosphere", code: "us" },
    { name: "Asia", code: "in" },
    { name: "Europe", code: "eu" },
    { name: "Middle East", code: "tr" },
    { name: "Americas", code: "ar" }
];

// Placeholder for parsed channels from your playlist.m3u8
let allChannels = [];
const player = videojs('tv-player');

async function initApp() {
    renderSidebar();
    await fetchChannels();
    loadRegion("Anglosphere");
}

function renderSidebar() {
    const list = document.getElementById('region-list');
    regions.forEach(reg => {
        const li = document.createElement('li');
        // Using the flag URL logic from make_flags.sh 
        li.innerHTML = `<img src="https://hatscripts.github.io/circle-flags/flags/${reg.code}.svg" width="20"> ${reg.name}`;
        li.onclick = () => loadRegion(reg.name);
        list.appendChild(li);
    });
}

async function fetchChannels() {
    // In production, you'd fetch the master playlist.m3u8 generated by your Python script
    // For this demo, we use the public URL derived from your provided files
    const response = await fetch('https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8');
    const text = await response.text();
    allChannels = parseM3U(text);
}

function parseM3U(data) {
    const lines = data.split('\n');
    const channels = [];
    let current = {};

    lines.forEach(line => {
        if (line.startsWith('#EXTINF')) {
            current.name = line.split(',')[1];
            current.logo = line.match(/tvg-logo="([^"]+)"/)?.[1];
            current.group = line.match(/group-title="([^"]+)"/)?.[1];
        } else if (line.startsWith('http')) {
            current.url = line;
            channels.push({ ...current });
            current = {};
        }
    });
    return channels;
}

function loadRegion(regionName) {
    const grid = document.getElementById('channel-grid');
    grid.innerHTML = '';

    const filtered = allChannels.filter(c => c.group === regionName);

    filtered.forEach(ch => {
        const card = document.createElement('div');
        card.className = 'channel-card';
        card.innerHTML = `
            <img src="${ch.logo}" onerror="this.src='https://via.placeholder.com/150x100?text=TV'">
            <p>${ch.name}</p>
        `;
        card.onclick = () => {
            player.src({ type: 'application/x-mpegURL', src: ch.url });
            player.play();
            document.getElementById('current-channel-name').innerText = ch.name;
        };
        grid.appendChild(card);
    });
}

initApp();